[package]
name = "manger"
version = "0.1.0"
edition = "2021"

[dependencies]

serde = { version = "1.0.100", features = ["derive"] }
serde_json = "1.0.79"
sycamore = { version = "0.8.0-beta.2", features = ["serde", "suspense"] }
sycamore-router = "0.8.0-beta.2"
uuid = { version = "0.8.2", features = ["serde", "v4", "wasm-bindgen"] }
wasm-bindgen = { version = "0.2.79", features = ["serde-serialize"]  }
wasm-bindgen-futures = "0.4.29"
rexie = "0.2.1"
reqwasm = "0.4.0"

[dependencies.web-sys]
features = [
    "InputEvent", "KeyboardEvent", "Location", "MediaQueryList", "Storage",
    "Window"
]
version = "0.3.56"