[package]
name = "manger"
version = "0.1.0"
edition = "2021"

[dependencies]

serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
sycamore = { version = "0.8.0-beta.2", features = ["serde"] }
sycamore-router = "0.8.0-beta.2"
uuid = { version = "0.8.2", features = ["serde", "v4", "wasm-bindgen"] }
wasm-bindgen = "0.2.79"
wasm-bindgen-futures = "0.4.26"
rexie = "0.2.1"

[dependencies.web-sys]
features = ["InputEvent", "KeyboardEvent", "Location", "MediaQueryList", "Storage", 'Headers', "Request", "RequestInit", "RequestMode", "Response", "Window"]
version = "0.3.56"